name: Build ESP32 from docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v5.4

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: build project
        run: 'echo "IDF_PATH: ${IDF_PATH}"'

